version: '3'

services:
    mariadb:
        image: cgr.dev/chainguard/mariadb
        ports:
            - '3306:3306'
        environment:
            MARIADB_DATABASE: skeema_test
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        volumes:
            - 'mariadb-data:/var/lib/mysql'
        networks:
            - skeema

    mysql8:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: skeema_test
        volumes:
            - 'mysql8-data:/var/lib/mysql'
        networks:
            - skeema
networks:
    skeema:
        driver: bridge
volumes:
    mariadb-data:
        driver: local
    mysql8-data:
        driver: local
